name: Monitor Notion API Changelog

on:
  schedule:
    # Runs every day at midnight (UTC)
    - cron: '0 0 * * *'

jobs:
  monitor-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install httpx PyGithub beautifulsoup4

      - name: Monitor Notion API Changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python .github/scripts/monitor_notion_changelog.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .github/scripts/known_entries.json
          git commit -m "Update known entries file [skip ci]" || echo "No changes to commit"
          git push
